spring.application.name=backend
spring.profiles.active=local
spring.data.mongodb.uri=mongodb+srv://indhumathirsj_db_user:indhu12345@cluster0.bev1svz.mongodb.net/nexusai?appName=Cluster0
server.port=8080

# Groq API Key
groq.api.key=${GROQ_API_KEY:}
